create table accommodation
(
    id       bigint generated by default as identity primary key,
    name     varchar(255),
    category varchar(50),
    host_id  bigint references host,
    numRooms integer,
    rented   boolean default false
);

create table country
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    continent varchar(255)
);

create table host
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references country
);

create table shop_users
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);


create table reservation
(
    id                 bigint generated by default as identity primary key,
    user_username      varchar(255) references shop_users,
    reservation_status varchar(50)
);

create table reservation_accommodations
(
    reservation_id    bigint references reservation on delete cascade,
    accommodations_id bigint references accommodation on delete cascade,
    primary key (reservation_id, accommodations_id)
);

create index idx_reservation_user_status on reservation (user_username, reservation_status);
create index idx_user_username_password on shop_users (username, password);
create index idx_user_username on shop_users (username);


